image: docker:latest

services:
  - docker:dind

before_script:
  - apk update && apk add git
  - docker login -u "$ACR_USERNAME" -p "$ACR_PASSWORD" $ACR_DOMAIN

build-development:
  stage: build
  script:
    - "docker build \
      --pull -t $ACR_DOMAIN/solidabis_app:development . "
    - docker push "$ACR_DOMAIN/solidabis_app:development"
  only:
    - development
